development:
  adapter: postgresql
  encoding: utf-8
  database: spa
  username: appsie
  password: Apsys20#
  host: localhost
  port: 5432
  schema_search_path: "mru,cru"

production:
  adapter: postgresql
  encoding: utf-8
  database: spa
  username: appsie
  password: Apsys20#
  host: localhost
  port: 5432
  schema_search_path: "mru,cru"